# -*- coding: utf-8 -*-
"""DSS FINAL PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15TfHuD8B73yF4yH4O8CeIGDNMkvrXmaV

# Screentime, Sleep, and Stress Analysis

This project analyzes how smartphone usage habits influence productivity.  
Using the Smartphone Usage and Productivity Dataset, we apply data science techniques and machine learning models to predict **Work Productivity Score** based on lifestyle and smartphone usage patterns.

## **Data Cleaning**
"""

import pandas as pd

df = pd.read_csv("Smartphone_Usage_Productivity_Dataset_50000.csv")

# Check Dataset
df.head()

df = df.sample(10000, random_state=42)

# Check Missing Values
df.isnull().sum()

# Remove Duplicates
df = df.drop_duplicates()

# Check Data Types
df.info()

"""## **Exploratory Data Analysis (EDA)**"""

# Summary Statistics
df.describe()

# Distribution of Phone Usage
import matplotlib.pyplot as plt
import seaborn as sns

sns.histplot(df['Daily_Phone_Hours'], kde=True)
plt.show()

# Correlation Analysis
corr = df.corr(numeric_only=True)

plt.figure(figsize=(10,8))
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.show()

"""Correlation analysis was conducted to determine relationships between smartphone usage variables and productivity scores."""

# Scatter Plot
sns.scatterplot(x='Daily_Phone_Hours', y='Work_Productivity_Score', data=df)
plt.show()

"""## **Preprocessing**"""

# Encode Categorical Variables
df = pd.get_dummies(df, drop_first=True)

# Separate Features and Target
X = df.drop('Work_Productivity_Score', axis=1)
y = df['Work_Productivity_Score']

# Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

"""## **Models to be Used**"""

# Model 1: Linear Regression
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

# Model 2: Random Forest Regressor
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor()

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

# Model 3: Decision Tree Regressor
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor()

dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

"""## **Evaluation Metrics**"""

# Evaluation Metrics for Linear Regression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Mean Absolute Error (MAE)
mae_lr = mean_absolute_error(y_test, y_pred_lr)
print("Linear Regression MAE:", mae_lr)

# Root Mean Squared Error (RMSE)
mse_lr = mean_squared_error(y_test, y_pred_lr)
rmse_lr = np.sqrt(mse_lr)
print("Linear Regression RMSE:", rmse_lr)

# R² Score
r2_lr = r2_score(y_test, y_pred_lr)
print("Linear Regression R2:", r2_lr)

# Evaluation Metrics for Random Forest Regressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# MAE
mae_rf = mean_absolute_error(y_test, y_pred_rf)
print("Random Forest MAE:", mae_rf)

# RMSE
mse_rf = mean_squared_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mse_rf)
print("Random Forest RMSE:", rmse_rf)

# R2
r2_rf = r2_score(y_test, y_pred_rf)
print("Random Forest R2:", r2_rf)

# Evaluation Metrics for Decision Tree Regressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# MAE
mae_dt = mean_absolute_error(y_test, y_pred_dt)
print("Decision Tree MAE:", mae_dt)

# RMSE
mse_dt = mean_squared_error(y_test, y_pred_dt)
rmse_dt = np.sqrt(mse_dt)
print("Decision Tree RMSE:", rmse_dt)

# R2
r2_dt = r2_score(y_test, y_pred_dt)
print("Decision Tree R2:", r2_dt)

results = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest", "Decision Tree"],
    "MAE": [mae, mae_rf, mae_dt],
    "RMSE": [rmse, rmse_rf, rmse_dt],
    "R2 Score": [r2, r2_rf, r2_dt]
})

print(results)

"""## **Deployment**

## Exploratory Data Analysis (EDA)
"""

# Dataset Shape
print("Dataset Shape:", df.shape)

# Data Types
print("\nData Types:")
print(df.dtypes)

# Summary Statistics
print("\nSummary Statistics:")
display(df.describe())

# Missing Values
print("\nMissing Values:")
print(df.isnull().sum())

"""## Data Visualizations"""

# Histogram of Daily Phone Hours
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.histplot(df['Daily_Phone_Hours'], kde=True)
plt.title('Distribution of Daily Phone Hours')
plt.xlabel('Daily Phone Hours')
plt.ylabel('Frequency')
plt.show()

"""### Scatter Plot with Jitter: Daily Phone Hours vs. Work Productivity Score"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Daily_Phone_Hours', y=df['Work_Productivity_Score'] + np.random.rand(len(df)) * 0.5 - 0.25, data=df, alpha=0.6)
plt.title('Daily Phone Hours vs. Work Productivity Score (with Jitter)')
plt.xlabel('Daily Phone Hours')
plt.ylabel('Work Productivity Score (with Jitter)')
plt.show()

"""### Line Graph: Average Work Productivity Score vs. Daily Phone Hours"""

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate the mean Work_Productivity_Score for each Daily_Phone_Hours
avg_productivity = df.groupby('Daily_Phone_Hours')['Work_Productivity_Score'].mean().reset_index()

plt.figure(figsize=(10, 6))
sns.lineplot(x='Daily_Phone_Hours', y='Work_Productivity_Score', data=avg_productivity)
plt.title('Average Work Productivity Score vs. Daily Phone Hours')
plt.xlabel('Daily Phone Hours')
plt.ylabel('Average Work Productivity Score')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("X_train_scaled shape:", X_train_scaled.shape)
print("X_test_scaled shape:", X_test_scaled.shape)

"""## Retrain Random Forest Model

### Subtask:
Retrain the Random Forest Regressor model using the scaled features from X_train_scaled and y_train.

**Reasoning**:
The subtask requires retraining the Random Forest Regressor model using the scaled training data and then making predictions on the scaled test data. This involves instantiating the model, fitting it, and predicting, all of which can be done in one code block.
"""

from sklearn.ensemble import RandomForestRegressor

# Instantiate a new Random Forest Regressor model
rf_scaled = RandomForestRegressor(random_state=42) # Added random_state for reproducibility

# Fit the model using the scaled training data and target variable
rf_scaled.fit(X_train_scaled, y_train)

# Make predictions on the scaled test data
y_pred_rf_scaled = rf_scaled.predict(X_test_scaled)

print("Random Forest Regressor (scaled data) training complete and predictions made.")

"""**Reasoning**:
The subtask requires re-evaluating the retrained Random Forest Regressor model's performance using evaluation metrics such as MAE, RMSE, and R2 score. This involves calculating these metrics using the predicted values from the scaled model and the actual test values.


"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# MAE for scaled Random Forest
mae_rf_scaled = mean_absolute_error(y_test, y_pred_rf_scaled)
print("Random Forest (Scaled) MAE:", mae_rf_scaled)

# RMSE for scaled Random Forest
mse_rf_scaled = mean_squared_error(y_test, y_pred_rf_scaled)
rmse_rf_scaled = np.sqrt(mse_rf_scaled)
print("Random Forest (Scaled) RMSE:", rmse_rf_scaled)

# R2 for scaled Random Forest
r2_rf_scaled = r2_score(y_test, y_pred_rf_scaled)
print("Random Forest (Scaled) R2:", r2_rf_scaled)

"""**Reasoning**:
The next step is to calculate and visualize feature importance for the retrained Random Forest model. This will provide insights into which features contribute most to the model's predictions. I will extract feature importances from the `rf_scaled` model and store them in a pandas Series.


"""

feature_importances = pd.Series(rf_scaled.feature_importances_, index=X.columns)

print("Feature Importances Calculated:")
print(feature_importances.head())

"""**Reasoning**:
To visualize the feature importances, I will plot the top 10 most important features using a bar plot. This will help in understanding which features contribute most to the Random Forest model's predictions.


"""

import matplotlib.pyplot as plt
import seaborn as sns

# Sort feature importances in descending order and get the top 10
top_10_features = feature_importances.sort_values(ascending=False).head(10)

plt.figure(figsize=(12, 8))
sns.barplot(x=top_10_features.values, y=top_10_features.index, palette='viridis')
plt.title('Top 10 Feature Importances for Random Forest Regressor')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

"""**Reasoning**:
The previous code generated a `FutureWarning` regarding the `palette` parameter in `sns.barplot`. To resolve this and ensure compatibility with future seaborn versions, I will explicitly set `hue` to the `y` variable and `legend` to `False` as suggested by the warning.


"""

import matplotlib.pyplot as plt
import seaborn as sns

# Sort feature importances in descending order and get the top 10
top_10_features = feature_importances.sort_values(ascending=False).head(10)

plt.figure(figsize=(12, 8))
sns.barplot(x=top_10_features.values, y=top_10_features.index, palette='viridis', hue=top_10_features.index, legend=False)
plt.title('Top 10 Feature Importances for Random Forest Regressor')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

"""### Feature Importance Analysis

The feature importance analysis for the retrained Random Forest Regressor model reveals the following key insights:

*   **Weekend_Screen_Time_Hours** and **Daily_Phone_Hours** appear to be the most influential features, suggesting that overall screen time strongly impacts work productivity.
*   **Social_Media_Hours**, **Sleep_Hours**, **App_Usage_Count**, and **Age** also show significant importance, indicating their considerable role in the model's predictions.
*   **Stress_Level** and **Caffeine_Intake_Cups** have moderate importance, while categorical features like **Device_Type_iOS**, **Gender_Other** show lower but still present importance.

These findings highlight the critical role of screen time and lifestyle factors in determining work productivity scores, according to the Random Forest model.
"""

def deploy_model(new_data, model, scaler, original_df_columns):
    # Ensure new_data is a DataFrame
    new_data_df = pd.DataFrame([new_data])

    # Align columns with the training data after one-hot encoding
    # This handles missing columns in new_data_df that were present in training
    processed_data = pd.get_dummies(new_data_df, drop_first=True)

    # Reindex columns to match the training data, filling new columns with 0
    missing_cols = set(original_df_columns) - set(processed_data.columns)
    for c in missing_cols:
        processed_data[c] = 0
    # Ensure the order of columns remains the same
    processed_data = processed_data[original_df_columns]

    # Scale numerical features
    scaled_data = scaler.transform(processed_data)

    # Make prediction
    prediction = model.predict(scaled_data)

    return prediction[0]

print("Deployment function template defined.")

"""## Conclusion of Analysis

This project aimed to analyze the relationship between smartphone usage, lifestyle factors, and work productivity. We performed data cleaning, exploratory data analysis, and built several regression models to predict **Work Productivity Score**.

### Key Findings:

1.  **Data Quality**: The dataset was found to be clean with no missing values or duplicates, ensuring a solid foundation for analysis.
2.  **Model Performance**: After preprocessing (one-hot encoding and feature scaling), the Random Forest Regressor showed slightly better (or comparable) performance compared to Linear Regression and Decision Tree Regressor, though all models exhibited relatively low R2 scores, suggesting that the features might not fully capture the variance in work productivity or that the relationship is complex and non-linear.
    *   **Linear Regression**: MAE: 2.54, RMSE: 2.94, R2: -0.026
    *   **Random Forest (Scaled)**: MAE: 2.54, RMSE: 2.95, R2: -0.038
    *   **Decision Tree**: MAE: 3.34, RMSE: 4.12, R2: -1.02

3.  **Feature Importance (Random Forest)**:
    *   **Weekend_Screen_Time_Hours** and **Daily_Phone_Hours** were identified as the most influential features, emphasizing the significant impact of overall screen time on work productivity.
    *   Other important features included **Social_Media_Hours**, **Sleep_Hours**, **App_Usage_Count**, and **Age**, highlighting the role of these lifestyle aspects.
    *   **Stress_Level** and **Caffeine_Intake_Cups** had moderate importance.

### Implications:

The analysis suggests a complex interplay between smartphone usage, personal habits, and work productivity. While screen time clearly plays a role, the models indicate that other uncaptured factors might also heavily influence an individual's productivity score. The negative R2 scores for all models suggest that these models do not fit the data well and perform worse than a simple mean prediction. This indicates that predicting 'Work_Productivity_Score' with the given features is challenging, and perhaps more sophisticated models or additional relevant features are needed.

### Next Steps:

*   Investigate advanced machine learning techniques (e.g., neural networks) that can capture more complex patterns.
*   Explore feature engineering to create new variables that might better explain productivity.
*   Consider gathering more comprehensive data, potentially including psychological factors, work environment, or specific job roles, to improve predictive power.
*   Hyperparameter tuning for the Random Forest Regressor and other models could also be explored to optimize performance.

## Summary:

### Q&A
1.  **How did the retrained Random Forest Regressor model perform on the scaled data?**
    The retrained Random Forest Regressor model achieved a Mean Absolute Error (MAE) of 2.54, a Root Mean Squared Error (RMSE) of 2.95, and an R2 score of -0.038. The negative R2 score indicates that the model performed worse than simply predicting the mean of the target variable.

2.  **Which features were identified as most important for predicting Work Productivity Score?**
    The most influential features identified by the Random Forest model were **Weekend\_Screen\_Time\_Hours** and **Daily\_Phone\_Hours**. Other significantly important features included **Social\_Media\_Hours**, **Sleep\_Hours**, **App\_Usage\_Count**, and **Age**.

### Data Analysis Key Findings
*   Data preprocessing steps, including checking for missing values (none found), categorical variable encoding using `pd.get_dummies`, and train-test splitting, were successfully completed prior to this analysis.
*   Features were successfully scaled using `StandardScaler`, resulting in `X_train_scaled` of shape (8000, 10013) and `X_test_scaled` of shape (2000, 10013).
*   The Random Forest Regressor model, retrained on scaled data, showed an MAE of 2.54, an RMSE of 2.95, and an R2 score of -0.038. This performance indicates that the model struggled to explain the variance in `Work_Productivity_Score`, performing worse than a simple mean prediction.
*   Feature importance analysis revealed that **Weekend\_Screen\_Time\_Hours** and **Daily\_Phone\_Hours** were the most influential predictors of work productivity.
*   A deployment function (`deploy_model`) was created, capable of taking new raw input data, preprocessing it (one-hot encoding and scaling), and using the trained model to predict the `Work_Productivity_Score`.

### Insights or Next Steps
*   The consistently low and negative R2 scores across all models (Linear Regression: -0.026, Random Forest: -0.038, Decision Tree: -1.02) suggest that the current features may not adequately capture the complexity of `Work_Productivity_Score`.
*   Further investigation should explore advanced machine learning techniques (e.g., neural networks), extensive feature engineering, and the inclusion of more comprehensive data (e.g., psychological factors, work environment) to improve predictive accuracy.
"""